### ISSUE TITLE
Inventory closes as soon as /invsee is executed

### ISSUE THREAD

**Issue by Shelly7w7** [BlockHorizons/InvSee#13]
X = Let's say a player

When I type ``/Invsee X`` The InventoryGUI Opens and closes rapidly. No error in console.

Using the latest Phar from Poggit CI. 

PocketMine version: 3.5.5

I also have installed virion and invmenu

**Comment by Muqsit** [comment]
And I assume `/enderinvsee X` works just fine?

**Comment by Shelly7w7** [comment]
@Muqsit Yeap.

**Comment by Wertzui123** [comment]
I think in the moment when the UI opens you are moving! You musn't move!

**Comment by Muqsit** [comment]
This bug is related to the InvMenu virion this plugin is using: https://github.com/Muqsit/InvMenu/issues/41
