### ISSUE TITLE
Cannot use after a reload

### ISSUE THREAD

**Issue by ReicitoE** [BlockHorizons/InvSee#23]
when you do /reload it stops working! you need to restart the server for it to work again! this really sucks! fix soon please!

**Comment by lukeeey** [comment]
The /reload command doesnt do what you would expect anyway, and it has been removed on 4.0 as it has little purpose. Since its very easy to get around this issue, i dont think we should look into it as it will be removed soon anyway.

**Comment by ReicitoE** [comment]
What do you mean? Reloading the server does exactly what i'd expect it to do.
