### ISSUE TITLE
/enderinvsee

### ISSUE THREAD

**Issue by HimmelKreis4865** [BlockHorizons/InvSee#24]
I can't modify my own inventory with the permission `invsee.enderinventory.modify.self`

I think it's a bug, so please give me an advice to fix it.
Would be nice to get help!

**Comment by Muqsit** [comment]
Hey, can you upload your InvSee phar here?

**Comment by HimmelKreis4865** [comment]
Yeah, here it is:
( I have to send a zip of it)
[InvSee.zip](https://github.com/BlockHorizons/InvSee/files/3528572/InvSee.zip)

**Comment by Muqsit** [comment]
Hey. I've just tested this using PurePerms by giving myself the `invsee.enderinventory.view` permission as non-op and executing `/enderinvsee <myself>` (everyone has the `invsee.enderinventory.modify.self` permission by default).
Works perfectly fine, check your permissions plugin.
