### ISSUE TITLE
PM4 Error

### ISSUE THREAD

**Issue by AIPTU** [BlockHorizons/InvSee#36]
Fatal error: Class BlockHorizons\InvSee\libs\muqsit\invmenu\inventory\InvMenuInventory 
cannot extend from interface pocketmine\block\inventory\BlockInventory in phar:///root/
aiptu/PocketMine-MP/master/server/plugins/InvSee_dev-47.phar/src/BlockHorizons/InvSee/l
ibs/muqsit/invmenu/inventory/InvMenuInventory.php on line 0

**Comment by Muqsit** [comment]
Fixed in https://github.com/BlockHorizons/InvSee/commit/f00beefed3bb2ba575e1296ed750a83639130b1d
