### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by SayaAEP** [BlockHorizons/InvSee#38]
![image](https://user-images.githubusercontent.com/91467886/163222148-f88ad64c-bca6-4fb5-ac96-f2bd52a45ed6.png)
I hope that after the 2.1.0 update ... has been implemented

**Comment by Muqsit** [comment]
Implemented in [(v2.1.1) InvSee_dev-71.phar](https://poggit.pmmp.io/r/171542/InvSee_dev-71.phar).
Set `command-player-selector-type` to `prefix-online` in `config.yml`.
https://github.com/BlockHorizons/InvSee/blob/18214b91f5e854ae4eb3246f3f57620430a42cdc/resources/config.yml#L1-L6

> * Added "portable-ender-chest" module - use /echest to access your own ender chest inventory
> * Added a configurable "command-player-selector-type" to allow targeting player by prefix in /invsee <player>, /enderinvsee <player> (f.e., "/invsee ste" to target "Steve")
> * Added a way to target players with spaces in name without using quotes (f.e., "/invsee steve gamer 3888" will target "Steve Gamer 3888")
> * Fix /enderinvsee <self> not working due to incorrect permission checking
> * Fix a memory leak in modules

**Comment by sayaaep** [comment]
![image](https://user-images.githubusercontent.com/91467886/163766521-e39f8ed5-d205-48d2-aea8-dd3eddd447ee.png)

work!
