### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Lil-Pandaa** [BlockHorizons/InvSee#40]
I would like to report this bug to the author of the plugin. https://youtu.be/HyPNI9y23PU

* Duplication Glitch *

**Comment by sayaaep** [comment]
yeah. but admins need logs from plugin (maybe)
and specific version plugin, php, pocketmine. etc

**Comment by Muqsit** [comment]
Yeah, that video is quite old and lacks the above information. Do send an updated recording along with the plugin and PM /version.
