### ISSUE TITLE
Server crashes when closing player's inventory

### ISSUE THREAD

**Issue by note3crafter** [BlockHorizons/InvSee#44]
PocketMine-MP Crash Dump Wed Jun 14 13:32:45 CEST 2023

PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.2.6
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: InvSee

Error: Cannot serialize a null itemstack
File: pmsrc/src/data/bedrock/item/ItemSerializer
Line: 94
Type: InvalidArgumentException
Backtrace:
#0 pmsrc/src/data/bedrock/item/ItemSerializer(134): pocketmine\data\bedrock\item\ItemSerializer->serializeType(object pocketmine\item\ItemBlock#195737)
#1 pmsrc/src/item/Item(707): pocketmine\data\bedrock\item\ItemSerializer->serializeStack(object pocketmine\item\ItemBlock#195737, null)
#2 plugins/InvSee.phar/src/BlockHorizons/InvSee/utils/OfflinePlayerInventory(150): pocketmine\item\Item->nbtSerialize()
#3 plugins/InvSee.phar/src/BlockHorizons/InvSee/player/handler/OfflineInvSeePlayerHandler(28): BlockHorizons\InvSee\utils\OfflinePlayerInventory->writeOffhandItem(object pocketmine\item\ItemBlock#195737)
#4 plugins/InvSee.phar/src/BlockHorizons/InvSee/player/InvSeePlayer(65): BlockHorizons\InvSee\player\handler\OfflineInvSeePlayerHandler->destroy(object BlockHorizons\InvSee\player\InvSeePlayer#195535)
#5 plugins/InvSee.phar/src/BlockHorizons/InvSee/player/InvSeePlayer(140): BlockHorizons\InvSee\player\InvSeePlayer->setHandler(object BlockHorizons\InvSee\player\handler\DestroyedInvSeePlayerHandler#193829)
#6 plugins/InvSee.phar/src/BlockHorizons/InvSee/player/InvSeePlayerList(77): BlockHorizons\InvSee\player\InvSeePlayer->destroy()
#7 plugins/InvSee.phar/src/BlockHorizons/InvSee/player/InvSeePlayerList(96): BlockHorizons\InvSee\player\InvSeePlayerList->destroy(object BlockHorizons\InvSee\player\InvSeePlayer#195535)
#8 plugins/InvSee.phar/src/BlockHorizons/InvSee/player/InvSeePlayer(99): BlockHorizons\InvSee\player\InvSeePlayerList->tryGarbageCollecting(string[10] ConCrafter71)
#9 plugins/InvSee.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/InvMenu(177): BlockHorizons\InvSee\player\InvSeePlayer->BlockHorizons\InvSee\player\{closure}(object pocketmine\player\Player#129256, object BlockHorizons\InvSee\libs\muqsit\invmenu\inventory\InvMenuInventory#195542)
#10 plugins/InvSee.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/InvMenuEventHandler(49): BlockHorizons\InvSee\libs\muqsit\invmenu\InvMenu->onClose(object pocketmine\player\Player#129256)
#11 pmsrc/src/event/RegisteredListener(61): BlockHorizons\InvSee\libs\muqsit\invmenu\InvMenuEventHandler->onInventoryClose(object pocketmine\event\inventory\InventoryCloseEvent#196553)
#12 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\inventory\InventoryCloseEvent#196553)
#13 pmsrc/src/player/Player(2618): pocketmine\event\Event->call()
#14 pmsrc/src/network/mcpe/InventoryManager(395): pocketmine\player\Player->removeCurrentWindow()
#15 pmsrc/src/network/mcpe/handler/InGamePacketHandler(723): pocketmine\network\mcpe\InventoryManager->onClientRemoveWindow(int 2)
#16 pmsrc/vendor/pocketmine/bedrock-protocol/src/ContainerClosePacket(46): pocketmine\network\mcpe\handler\InGamePacketHandler->handleContainerClose(object pocketmine\network\mcpe\protocol\ContainerClosePacket#221376)
#17 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\ContainerClosePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#140618)
#18 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ContainerClosePacket#221376, string[3] /..)
#19 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[6] c.gb..)
#20 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[15] ..`..x.&..y....)
#21 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#163296)
#22 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#23 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#24 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#25 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686742365.3324)
#26 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#27 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[17] /home/CyberCraft/, string[25] /home/CyberCraft/plugins/)
#28 pmsrc/src/PocketMine(357): pocketmine\server()
#29 pmsrc(11): require(string[61] phar:///home/CyberCraft/PocketMine-MP.phar/src/PocketMine.php)

Code:
[85] 
[86] 	/**
[87] 	 * @phpstan-template TItemType of Item
[88] 	 * @phpstan-param TItemType $item
[89] 	 *
[90] 	 * @throws ItemTypeSerializeException
[91] 	 */
[92] 	public function serializeType(Item $item) : Data{
[93] 		if($item->isNull()){
[94] 			throw new \InvalidArgumentException("Cannot serialize a null itemstack");
[95] 		}
[96] 		if($item instanceof ItemBlock){
[97] 			$data = $this->serializeBlockItem($item->getBlock());
[98] 		}else{
[99] 			$index = $item->getTypeId();
[100] 
[101] 			$locatedSerializer = $this->itemSerializers[$index] ?? null;
[102] 			if($locatedSerializer === null){
[103] 				throw new ItemTypeSerializeException("No serializer registered for " . get_class($item) . " ($index) " . $item->getName());
[104] 			}

**Comment by sayaaep** [comment]
wait what pm5 was exist?
